apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-dns-external
  namespace: cis-dns
  labels:
    app: cis-dns-external
spec:
  selector:
    matchLabels:
      app: cis-dns-external
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cis-dns-external
      annotations: {}
    spec:
      volumes:
        - name: dns-config
          configMap:
            name: cis-dns
      initContainers:
      - name: test-dns
        image: ghcr.io/mike-matera/cis-infrastructure:dns-2022061601
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "external"
        volumeMounts:
        - name: dns-config
          mountPath: /cis-dns/source
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        command: ['sh', '-c', "./test.sh"]
      containers:
      - name: cis-dns-external
        image: ghcr.io/mike-matera/cis-infrastructure:dns-2022061601
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "external"
        volumeMounts:
        - name: dns-config
          mountPath: /cis-dns/source
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-dns-internal
  namespace: cis-dns
  labels:
    app: cis-dns-internal
spec:
  selector:
    matchLabels:
      app: cis-dns-internal
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cis-dns-internal
      annotations: {}
    spec:
      volumes:
        - name: dns-config
          configMap:
            name: cis-dns
      initContainers:
      - name: test-dns
        image: ghcr.io/mike-matera/cis-infrastructure:dns-2022061601
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "internal"
        volumeMounts:
        - name: dns-config
          mountPath: /cis-dns/source
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        command: ['sh', '-c', "./test.sh"]
      containers:
      - name: cis-dns-internal
        image: ghcr.io/mike-matera/cis-infrastructure:dns-2022061601
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "internal"
        volumeMounts:
        - name: dns-config
          mountPath: /cis-dns/source
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
