#
# This role configures LXD on a bare metal host. 
#
    
- name: Install LXD by snap
  become: true
  snap:
    name:
      - lxd

- name: remove the LXD package
  become: true
  apt:
    name: lxd
    state: absent
    purge: yes 

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Check if the local storage pool has been configured.
  shell: lxc storage list | grep -q local 
  register: do_lxd_init 
  ignore_errors: True 
  changed_when: False 

- name: Initialize LXD 
  become: true
  shell: 
    cmd: /snap/bin/lxd init --preseed
    stdin: "{{ lxd_preseed }}"
  when: do_lxd_init.rc == 1
