# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'pathname'

# Change this if you want to add or remove extra disks. 
num_cluster = 3
num_disks = 2
image = "ubuntu/bionic64"
memory = "4096"
playbook = "playbook.yaml"

Vagrant.configure("2") do |config|
    config.vm.box = image
    config.vm.box_check_update = false

    (1..num_cluster).each do |num| 
        name = 'c' + num.to_s
        config.vm.define name do |clus|
            clus.vm.hostname = name
            clus.vm.network :private_network, ip: "10.0.0.#{num + 100}"
            clus.vm.provider "virtualbox" do |vb|
                vb.memory = memory
                if num_disks > 0 and not File.exist?(name + '-extra-0.vdi')
                    vb.customize ['storagectl', :id, '--name', 'VirtIO', '--add', 'virtio', '--controller', 'VirtIO']
                end
                (1..num_disks).each do |i|
                    disk = name + '-extra-' + i.to_s + '.vdi'
                    if not File.exist?(disk)
                        vb.customize ['createmedium', '--filename', disk, '--variant', 'Fixed', '--size', 1024]
                    end
                    vb.customize ['storageattach', :id,  '--storagectl', 'VirtIO', '--port', i, '--device', 0, '--type', 'hdd', '--medium', disk]
                end
            end
            if File.exist?(playbook)
                # Run Ansible from the Vagrant VM
                clus.vm.provision "ansible_local" do |ansible|
                    ansible.playbook = playbook
                end
            end
        end
    end
end
