#
# Create admin accounts on opus (and possibly other login servers).
#
# Accounts are created without passwords, only SSH keys.
#

- name: Add the user "{{ user }}"
  become: yes
  user:
    name: "{{ user }}"
    shell: /bin/bash
    home: "/home/{{ user }}"
    groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev
    append: yes

- name: Add keys for "{{ user }}""
  become: yes
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "https://github.com/{{ gitHubID }}.keys"

- name: Create kubernetes directory
  become: yes
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Add the admin to passwordless SUDO 
  become: yes
  blockinfile: 
    path: /etc/sudoers.d/90-cloud-init-users
    block: |
      "{{ user }}" ALL=(ALL) NOPASSWD:ALL

