
- hosts: all 
  name: Configure networking 
  become: true
  tags:
    - network
  roles:
    - firewall:
      role: ../../ansible-common/roles/firewall 
      vars:
        policy: deny 
        logging: on
        rateLimiting: limit 
        allowSSH: allow 
        deleteSSH: no 
        allowHttp: deny
        allowHttps: deny
    - admins:
      role: ../../ansible-common/roles/admin
      vars:
        user: mmatera
        gitHubID: mike-matera 
    - netplan:
      role: ../../ansible-common/roles/netplan 
      vars:
        primary_interface: cisnet        

- hosts: all 
  name: Allow LXC to communicate over the network.
  become: true
  tags:
    - network
  tasks:
    - name: Allow LXC port
      community.general.ufw:
        rule: allow
        port: "8443"
        proto: tcp

- hosts: dell-r620-1.maas 
  name: Configure networking 
  become: true
  tags:
    - lxd
  roles:
    - lxd:
      role: ../../ansible-common/roles/lxd
      vars:
        lxd_preseed: |
          config:
            core.https_address: 192.168.0.145:8443
          networks: []
          storage_pools:
          - config:
              source: /dev/sdb
            description: ""
            name: local
            driver: zfs
          profiles:
          - config: {}
            description: ""
            devices:
              eth0:
                name: eth0
                nictype: bridged
                parent: server
                type: nic
              root:
                path: /
                pool: local
                type: disk
            name: default
          projects: []
          cluster:
            server_name: dell-r620-1
            enabled: true
            member_config: []
            cluster_address: ""
            cluster_certificate: ""
            server_address: ""
            cluster_password: ""
            cluster_certificate_path: ""
            cluster_token: ""


- hosts: all 
  name: Connect this host to the LXD daemon.
  become: true
  tags:
    - lxd-login
  tasks:
    - name: Enable temporary password 
      ansible.builtin.shell: lxc config set core.trust_password "asjdfalsjdfv0349jhuisadnvasukdnv"
    - name: Login locally  
      ansible.builtin.shell: lxc remote add lxc-cluster dell-r620-1.maas --accept-certificate --password "asjdfalsjdfv0349jhuisadnvasukdnv"
      ignore_errors: yes
      become: no
      delegate_to: 127.0.0.1
    - name: Remove temporary password 
      ansible.builtin.shell: lxc config unset core.trust_password
