---
apiVersion: v1
kind: Service
metadata:
  name: cis-dns-external
  labels:
    app: cis-dns-external
spec:
  selector:
    app: cis-dns-external
  ports:
    - name: dns
      port: 53
      protocol: UDP 
    - name: dns-tcp
      port: 53
      protocol: TCP
  externalIPs:
    - 172.30.5.252
    - 172.30.5.253
---
apiVersion: v1
kind: Service
metadata:
  name: cis-dns-internal
  labels:
    app: cis-dns-internal
spec:
  selector:
    app: cis-dns-internal
  ports:
    - name: dns
      port: 53
      protocol: UDP 
    - name: dns-tcp
      port: 53
      protocol: TCP
  externalIPs:
    - 172.30.5.101
    - 172.30.5.102
