apiVersion: v1
kind: Service
metadata:
  name: cis-mail
  labels:
    app: cis-mail
spec:
  selector:
    app: cis-mail
  ports:
    - name: smtp
      port: 25
      protocol: TCP 
  externalIPs:
    - 172.30.5.252
