apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-mail
  labels:
    app: cis-mail
spec:
  selector:
    matchLabels:
      app: cis-mail
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cis-mail
      annotations:
    spec:
      containers:
      - name: cis-mail
        image: mikematera/cis-mail:2020082201
        imagePullPolicy: IfNotPresent
        env:
          - name: MAILNAME
            value: "mail.cis.cabrillo.edu"
          - name: MYNETWORKS
            value: "10.0.0.0/8"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
