#The variables for this role are located in inventories/maas. In the hosts.yaml file
#each machine can specify its own firewall regulations by changing the value of the variable with one
#of the given values listed right above it.
#
#

- name: Enable the firewall
  become: yes
  community.general.ufw:
    state: enabled
    policy: "{{ policy }}"

- name: Set logging
  become: yes
  community.general.ufw:
    logging: "{{logging}}"
  
  
- name: Connection rate limiting
  become: yes
  community.general.ufw:
    rule: "{{ rateLimiting }}"
    port: ssh
    proto: tcp

- name: Allow SSH
  become: yes
  community.general.ufw:
    rule: "{{ allowSSH }}"
    name: OpenSSH

- name: Delete OpenSSH rule
  become: yes
  community.general.ufw:
    rule: allow
    name: OpenSSH
    delete: "{{ deleteSSH }}"

- name: Allow HTTP
  become: yes
  community.general.ufw:
    rule: "{{ allowHttp }}"
    port: '80'
    proto: tcp

- name: Allow HTTPS
  become: yes
  community.general.ufw:
    rule: "{{ allowHttps }}"
    port: '443'
    proto: tcp

- name: Deny all access to port 53
  become: yes
  community.general.ufw:
    rule: "{{ denyPort53 }}"
    port: '53'