
- name: netplan apply 
  become: yes
  shell: netplan apply
- name: netplan apply reboot
  become: yes
  shell: netplan apply
  notify: reboot after netplan apply 
- name: reboot after netplan apply
  become: yes
  reboot:
    reboot_timeout: 600
