
- hosts: all 
  name: Configure networking 
  become: true
  tags:
    - network
  roles:
    - firewall:
      role: ../../ansible-common/roles/firewall 
      vars:
        policy: deny 
        logging: on
        rateLimiting: limit 
        allowSSH: allow 
        deleteSSH: no 
        allowHttp: deny
        allowHttps: deny
    - admins:
      role: ../../ansible-common/roles/admin
      vars:
        user: mmatera
        gitHubID: mike-matera 
    - netplan:
      role: ../../ansible-common/roles/netplan 
      vars:
        primary_interface: cisnet        

- hosts: all
  name: Configure the hosts. 
  become: true
  tags:
    - host
  tasks:
  - ansible.posix.sysctl:
      name: fs.inotify.max_user_watches
      value: '1048576'
      sysctl_set: yes
  - ansible.posix.sysctl:
      name: fs.inotify.max_user_instances
      value: '512'
      sysctl_set: yes

- hosts: all
  name: Install microk8s. 
  become: true
  roles:
    - microk8s:
      role: ../../ansible-common/roles/microk8s

- hosts: proliant-2.maas
  name: Join the cluser
  become: true
  tags:
    - join
  roles:
    - microk8s-join:
      role: ../../ansible-common/roles/microk8s-join
      vars:
        leader_login: 'ubuntu@proliant-1.maas'

- hosts: proliant-3.maas
  name: Join the cluser
  become: true
  tags:
    - join
  roles:
    - microk8s-join:
      role: ../../ansible-common/roles/microk8s-join
      vars:
        leader_login: 'ubuntu@proliant-1.maas'

- hosts: proliant-4.maas
  name: Join the cluser
  become: true
  tags:
    - join
  roles:
    - microk8s-join:
      role: ../../ansible-common/roles/microk8s-join
      vars:
        leader_login: 'ubuntu@proliant-1.maas'

- hosts: proliant-1.maas
  name: Configure microk8s
  become: true
  tags:
    - microk8s-config
  tasks:
    - name: Enable Community add-ons
      shell: /snap/bin/microk8s enable community
    - name: Enable RBAC
      shell: /snap/bin/microk8s enable rbac
    - name: Enable Helm v3
      shell: /snap/bin/microk8s enable helm3 
    - name: Enable kube dns.
      shell: /snap/bin/microk8s enable dns 
    - name: Enable MetalLB
      shell: /snap/bin/microk8s enable metallb:172.30.5.100-172.30.5.150,172.30.5.240-172.30.5.254
    - name: Enable Ingress
      shell: /snap/bin/microk8s enable ingress 
    - name: Enable dashboard
      shell: /snap/bin/microk8s enable dashboard 
    - name: Enable Mayastor
      shell: /snap/bin/microk8s enable core/mayastor
    - name: Enable OpenEBS/cStor
      shell: /snap/bin/microk8s enable community/openebs
