---
# 
# Playbook for the Dell R630-1 Machine
#
# This machine is now clustered.
#

- hosts: dell-r630-1
  name: Apply networking configuration
  become: yes
  tags:
    - netplan
  roles:
    - netplan 
  tasks:
  - name: Add CIS Networking Bridge Configuration
    become: yes
    template:
      src: hostfiles/dell-r630-1/99-host-config.yaml
      dest: /etc/netplan
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  - name: netplan apply 
    shell: netplan apply

### Manually create the LVM system for this host 
## It's not like the others. 
- hosts: dell-r630-1
  name: Apply LVM Configuraiton
  become: yes
  tags:
    - disks
  roles:
    - lvm 
  tasks:
    - name: Create a volume for 
      lvol:
        vg: vg-ssd
        lv: container-data
        size: 900g
        opts: --type raid1 
    - name: Create a ext4 filesystem for the host path provisioner
      filesystem:
        fstype: ext4
        dev: /dev/vg-ssd/container-data
    - name: Create the /data/hostpath directory
      file:
        path: /data/hostpath
        state: directory
        mode: '0755'        
    - name: Mount home data directory
      mount:
        path: /data/hostpath
        src: /dev/vg-ssd/container-data
        fstype: ext4
        state: mounted
  
- hosts: dell-r630-1
  name: Install and configure Microk8s 
  become: yes
  tags:
    - microk8s
  roles:
    - role: microk8s 
      vars:
        lb_ip_range: 172.30.5.230/32

- hosts: dell-r630-1
  name: Configure the firewall 
  become: yes
  tags:
    - firewall
  tasks:
    - name: Allow traffic from the server network.
      become: yes
      ufw:
        rule: allow
        src: 172.30.5.0/24
    - name: Allow SSH 
      ufw:
        rule: allow
        port: ssh
        proto: tcp
    - ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Enable the firewall 
      ufw:
        state: enabled
        policy: deny
