---
# 2021 owner: Michael
# Playbook for the Dell R610-2 Machine
#
# This machine is deployed by MAAS
#

- hosts: dell-r610-2
  name: Apply networking configuration
  remote_user: ubuntu
  roles:
    - netplan 

- hosts: dell-r610-2
  name: Apply disk layout and install LXD
  remote_user: ubuntu
  roles:
    - lvm
    - lxd
    - test_firewall
    - test_admin

    - role: lxd_server
      vars:
        userName: testopus
        nicName: eth0
        nictype: bridged
        parent: server
        hwaddr: aa:99:55:00:00:01
        size: 100GB
        distro: 'ubuntu:18.04'
        netconfig: | 
          network:
            ethernets:
                eth0:
                  addresses:
                    - 172.30.5.235/24
                    - 2607:F380:80F:F425::235/64
                  gateway4: 172.30.5.1
                  nameservers:
                    search: [cis.cabrillo.edu]
                    addresses: [172.30.5.101, 172.30.5.102]