all:
  hosts:
    dell-r630-1:
      ansible_host: 192.168.0.130
      ansible_user: ubuntu 
      primary_interface: cisnet
      device_ssd: /dev/sdc,/dev/sdd
      device_hdd: /dev/sdg,/dev/sdh
    supermicro-1:
      ansible_host: supermicro-1.maas
      ansible_user: ubuntu 
      primary_interface: cisnet
      device_ssd: /dev/sda 
      device_hdd: /dev/sdb 
    supermicro-2:
      ansible_host: supermicro-2.maas
      ansible_user: ubuntu 
      primary_interface: cisnet
      device_ssd: /dev/sda 
      device_hdd: /dev/sdb 
    supermicro-3:
      ansible_host: supermicro-3.maas
      ansible_user: ubuntu 
      primary_interface: cisnet
      device_ssd: /dev/sda 
      device_hdd: /dev/sdb 
    dell-r620-1:
      ansible_host: 192.168.0.134
      primary_interface: cisnet
      device_ssd: /dev/sda2 
      device_hdd: /dev/sdb
      vg_disk_pool_size: 500
      vg_disk_home_size: 128
    dell-r620-2:
      ansible_host: 192.168.0.135
      primary_interface: cisnet
      device_ssd: /dev/sda2 
      device_hdd: /dev/sdb
    dell-r610-1:
      ansible_host: 192.168.0.136
      primary_interface: cisnet
    dell-r610-2:
      ansible_host: 192.168.0.137
      primary_interface: cisnet
      device_ssd: /dev/sda2
      device_hdd: /dev/sdb
      vg_disk_pool_size: 150
      vg_disk_home_size: 70
    dell-r610-3:
      ansible_host: 192.168.0.138
      primary_interface: cisnet
      device_ssd: /dev/sda2 
      device_hdd: /dev/sdb
      vg_disk_pool_size: 100
      vg_disk_home_size: 100
  children:
    maas:
      hosts:
        dell-r630-1:
        supermicro-1:
        supermicro-2:
        supermicro-3:
        dell-r620-1:
        dell-r620-2:
        dell-r610-1:
        dell-r610-2:
        dell-r610-3:
    dell-r630:
      hosts:
        dell-r630-1:
    supermicro:
      hosts:
        supermicro-1:
        supermicro-2:
        supermicro-3:
    dell-r620:
      hosts:
        dell-r620-1:
        dell-r620-2:
    dell-r610:
      hosts:
        dell-r610-1:
        dell-r610-2:
          user: machavez
          gitHubID: chavezMac
          policy: deny #{policy:allow,deny,reject}
          logging: "on" #{logging:"on,off,low,medium,high,full"}
          rateLimiting: limit #{rule:allow,deny,limit,reject}
          allowSSH: allow  #{rule:allow,deny,limit,reject}
          deleteSSH: "yes" #{delete:yes,no}
          allowHttp: allow #{rule:allow,deny,limit,reject}
          allowHttps: allow #{rule:allow,deny,limit,reject}
          denyPort53: deny #{rule:allow,deny,limit,reject}
        dell-r610-3:
    student-cluster:
      hosts:
        dell-r630-1:
        supermicro-1:
        supermicro-2:
        supermicro-3:
