#
# Create the "{{ lxc_hostname }}" container in LXD.
#
# This assumes lxd has been setup according to the lxd role.
# Home directories will be shared with the host. 
#

- name: "Create {{ lxc_hostname }} home directories."
  become: true
  file:
    path: "/data/homes/{{ lxc_hostname }}"
    state: directory
    mode: '0755'
    owner: '1000000'
    group: '1000000'
   
- name: "Create the {{ lxc_hostname }} profile."
  community.general.lxd_profile:
    name: "{{ lxc_hostname }}"
    state: present
    config: 
      user.network-config: "{{ cloud_init_network }}"
      user.user-data: "{{ cloud_init_user }}"
      security.nesting: "true"
    description: "Profile for {{ lxc_hostname }}"
    devices:
      eth0:
        name: eth0
        nictype: bridged
        parent: server
        type: nic
      homes:
        path: /home
        source: "/data/homes/{{ lxc_hostname }}"
        type: disk
      root:
        path: /
        pool: local
        size: "{{ rootfs_size }}"
        type: disk


- name: "Create the {{ lxc_hostname }} container."
  community.general.lxd_container:
    name: "{{ lxc_hostname }}"
    ignore_volatile_options: true
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams 
      alias: "{{ distro }}"
    profiles: [ "{{ lxc_hostname }}" ]

